<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Evaluar</name>
  <uuid>ac4f0aff-8871-4a26-9fc7-20d616477b37</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Edad is at least 18 and less than 75
then
    set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
